CREATE TABLE AREA (
    ID_AREA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL
);
CREATE TABLE MEDICO (
    ID_MEDICO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    ESPECIALIDAD VARCHAR2(50),
    TELEFONO VARCHAR2(15),
    ID_AREA NUMBER,
    CONSTRAINT FK_MEDICO_AREA FOREIGN KEY (ID_AREA)
        REFERENCES AREA(ID_AREA)
);
CREATE TABLE PACIENTE (
    ID_PACIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    DNI VARCHAR2(8),
    TELEFONO VARCHAR2(15),
    DIRECCION VARCHAR2(100)
);
CREATE TABLE CITA (
    ID_CITA NUMBER PRIMARY KEY,
    FECHA_CITA DATE,
    MOTIVO VARCHAR2(100),
    ID_PACIENTE NUMBER,
    ID_MEDICO NUMBER,
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (ID_PACIENTE)
        REFERENCES PACIENTE(ID_PACIENTE),
    CONSTRAINT FK_CITA_MEDICO FOREIGN KEY (ID_MEDICO)
        REFERENCES MEDICO(ID_MEDICO)
);
CREATE TABLE HISTORIAL_CLINICO (
    ID_HISTORIAL NUMBER PRIMARY KEY,
    DIAGNOSTICO VARCHAR2(200),
    TRATAMIENTO VARCHAR2(200),
    ID_PACIENTE NUMBER,
    CONSTRAINT FK_HISTORIAL_PACIENTE FOREIGN KEY (ID_PACIENTE)
        REFERENCES PACIENTE(ID_PACIENTE)
);
COMMIT;
